version: "3.9"

services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: root1234
      MARIADB_DATABASE: delivery
      MARIADB_USER: delivery
      MARIADB_PASSWORD: delivery1234

    ports:
      - "33060:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot1234"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data: