spring.application.name=orderService
server.port=8080

# ===========================
# MariaDB
# ===========================
spring.datasource.url=jdbc:mariadb://localhost:33060/order_db
spring.datasource.username=delivery
spring.datasource.password=delivery1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ===========================
# JPA
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# =======================================================
# Kafka
# =======================================================
# 1. 카프카 브로커 주소(도커)
spring.kafka.bootstrap-servers=127.0.0.1:19094, 127.0.0.1:29094, 127.0.0.1:39094
# 2. 컨슈머(수신자) 설정
# 컨슈머 그룹 ID
spring.kafka.consumer.group-id=order-group
# 초기 오프셋이 없을 때 가장 처음부터 읽기
spring.kafka.consumer.auto-offset-reset=latest
# Key/Value 역직렬화 클래스 (문자열 기준)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# 3. 프로듀서(송신자) 설정
# Key/Value 직렬화 클래스 (문자열 기준)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# 멱등성 true
spring.kafka.producer.properties.enable.idempotence=true
# ack 수 2/3
spring.kafka.producer.acks=all
# 발행 리트라이 수
spring.kafka.producer.retries=3
# 한 번에 보낼 수 있는 최대 요청 수
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5